In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
k = 5
A = np.eye(k)
A[-1, :] = -1
A[-1, -1] = 0
A

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [-1., -1., -1., -1.,  0.]])

In [3]:
U, S, Vt = np.linalg.svd(A)
U, S, Vt

(array([[-2.23606798e-01,  8.66025404e-01,  2.16917671e-17,
          1.01656441e-16,  4.47213595e-01],
        [-2.23606798e-01, -2.88675135e-01,  0.00000000e+00,
          8.16496581e-01,  4.47213595e-01],
        [-2.23606798e-01, -2.88675135e-01,  7.07106781e-01,
         -4.08248290e-01,  4.47213595e-01],
        [-2.23606798e-01, -2.88675135e-01, -7.07106781e-01,
         -4.08248290e-01,  4.47213595e-01],
        [ 8.94427191e-01, -7.18288031e-17,  2.16917671e-17,
          1.01656441e-16,  4.47213595e-01]]),
 array([2.23606798, 1.        , 1.        , 1.        , 0.        ]),
 array([[-5.00000000e-01, -5.00000000e-01, -5.00000000e-01,
         -5.00000000e-01,  0.00000000e+00],
        [ 8.66025404e-01, -2.88675135e-01, -2.88675135e-01,
         -2.88675135e-01,  0.00000000e+00],
        [-0.00000000e+00,  8.75605293e-17,  7.07106781e-01,
         -7.07106781e-01, -0.00000000e+00],
        [ 0.00000000e+00,  8.16496581e-01, -4.08248290e-01,
         -4.08248290e-01,  0.0000000

In [4]:
Q, R = np.linalg.qr(A)
Q, R

(array([[-0.70710678,  0.40824829,  0.28867513,  0.2236068 ,  0.4472136 ],
        [-0.        , -0.81649658,  0.28867513,  0.2236068 ,  0.4472136 ],
        [-0.        ,  0.        , -0.8660254 ,  0.2236068 ,  0.4472136 ],
        [-0.        ,  0.        ,  0.        , -0.89442719,  0.4472136 ],
        [ 0.70710678,  0.40824829,  0.28867513,  0.2236068 ,  0.4472136 ]]),
 array([[-1.41421356, -0.70710678, -0.70710678, -0.70710678,  0.        ],
        [ 0.        , -1.22474487, -0.40824829, -0.40824829,  0.        ],
        [ 0.        ,  0.        , -1.15470054, -0.28867513,  0.        ],
        [ 0.        ,  0.        ,  0.        , -1.11803399,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]))

In [5]:
np.round(Q @ Q.T), np.round(Q.T @ Q)

(array([[ 1., -0.,  0.,  0.,  0.],
        [-0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  1.]]),
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]))

In [6]:
Qr = Q[:, :-1]
Qr

array([[-0.70710678,  0.40824829,  0.28867513,  0.2236068 ],
       [-0.        , -0.81649658,  0.28867513,  0.2236068 ],
       [-0.        ,  0.        , -0.8660254 ,  0.2236068 ],
       [-0.        ,  0.        ,  0.        , -0.89442719],
       [ 0.70710678,  0.40824829,  0.28867513,  0.2236068 ]])

In [7]:
np.round(Qr @ Qr.T, 4), np.round(Qr.T @ Qr, 4)

(array([[ 0.8, -0.2, -0.2, -0.2, -0.2],
        [-0.2,  0.8, -0.2, -0.2, -0.2],
        [-0.2, -0.2,  0.8, -0.2, -0.2],
        [-0.2, -0.2, -0.2,  0.8, -0.2],
        [-0.2, -0.2, -0.2, -0.2,  0.8]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [11]:
k = 4
A = np.eye(k)
A[-1, :] = -1
A[-1, -1] = 0
U, S, Vt = np.linalg.svd(A)
A_Q = U[:, :-1]
np.round(A_Q, decimals=3)

array([[-0.289,  0.816,  0.   ],
       [-0.289, -0.408,  0.707],
       [-0.289, -0.408, -0.707],
       [ 0.866,  0.   ,  0.   ]])

In [19]:
one_k = np.ones((k, 1))

In [12]:
from scipy.linalg import null_space

In [15]:
Z = null_space(np.ones((1, k)))